### ISSUE TITLE
Update build instructions

### ISSUE THREAD

**Issue by Jason2605** [dictu-lang/Dictu#284]
# Update build instructions
As of #278 CMake was introduced as a method for building Dictu. The README currently only describes how to build using the older makefile, we should extend the README (as well as the site documentation) to show how to build Dictu with CMake as well.

**Comment by TheGreatCookieMachine** [comment]
(All terminal commands are shown assuming the current directory is Dictu's.)

## Author's Note

None of what I wrote here is intended to be put into the Readme or documentation, rather it is meant to be an accessible demonstration of the CMake CLI in the context of Dictu for those who wish to write the documentation. A lot of what is written here is written in more detail than is necessary.

This also ended up being way longer than I intended it to be. Sorry about that.

## Prologue

Building using CMake can be somewhat odd due to the fact that CMake is not a build file but rather a build file generator. This means its a two steps process: generate the build file and then use the build file. It is also further complicated by the fact that the CLI is not the only way to use CMake. On Windows, there is also CMake-GUI. Many IDEs also have support for CMake, with interaction methods differing from the CLI. Personally, I use VSCode with CMake-Tools. However, for simplicities sake I will just focus on the CLI.

## Generating the build file

### Basic Building

The first step is generating build files. To do so is fairly simple:

```
cmake ./
```

However, that clutters the main folder. If you want to send the new files into a build folder you can do this:

```
cmake -S ./ -B ./build
```

I wholeheartedly recommend doing it this way. Depending of the chosen generator, there may be numerous files and folders which are generated. It also makes it more difficult to remove the generated files if needed. Rather than just deleting the build folder, you have to pick and choose individual files.

### Options

To disable HTTPS and Linenoise, you do this:

```
<Previously mentioned setup> -D DISABLE_HTTP=TRUE -D DISABLE_LINENOISE=TRUE
```

If you want to ensure it is compiled as debug:

```
<Previously mentioned setup> -D CMAKE_BUILD_TYPE=DEBUG
```

Or if you want it to be release:

```
<Previously mentioned setup> -D CMAKE_BUILD_TYPE=RELEASE
```

### Generators

If you want to specify which generator file is generated, you can do so like so:

```
<Previously mentioned setup> -G "<generator>"
```

Where `<generator>` is a valid generator listed here: https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#manual:cmake-generators(7)

### CMakeCache

When CMake generates a build file, it also generates a cache in the build directory. The cache saves the above settings to allow easier building for future builds.

```
cmake -D DISABLE_HTTP=TRUE -D DISABLE_LINENOISE=TRUE -D CMAKE_BUILD_TYPE=DEBUG -G "MinGW Makefiles" -S ./ -B ./build
cmake -S ./ -B ./build
```

If the first command is run before the second command, the two commands are equivalent. It also allows for changing of individual variables:

```
cmake -D DISABLE_HTTP=TRUE -D DISABLE_LINENOISE=TRUE -D CMAKE_BUILD_TYPE=DEBUG -G "MinGW Makefiles" -S ./ -B ./build
cmake -D CMAKE_BUILD_TYPE=RELEASE -S ./ -B ./build
```

This first builds a debug build and then a release build. Although I didn't specify the most of the variables in the second call, they remain the same as what they were in the first call.

CMake caches also allow simpler directing of the CMake program. Rather than specifying the source directory and the build directory, you can simply specify the build directory.

```
cmake -D DISABLE_HTTP=TRUE -D DISABLE_LINENOISE=TRUE -D CMAKE_BUILD_TYPE=DEBUG -G "MinGW Makefiles" -S ./ -B ./build
cmake -D CMAKE_BUILD_TYPE=RELEASE ./build
```

I specify both in the first call, but only specify the build directory in the second.

There is no way to directly remove the Cache, however if you sent the build files to their own directory you can simply delete the directory.

## Building the build file

After you do that, you build the new build files. You can do so manually (For instance, if you generated a makefile, you can manually use make). Or, you can let CMake automatically dispatch to the correct program. If you sent the build files into the same directory:

```
cmake --build ./
```

If you sent it to the build directory:

```
cmake --build ./build
```

It is important to note that the executable may be in different places based upon which generator you used. When I use Visual Studio, the executable is in `./build/Debug/Dictu.exe` for debug builds. When I use MinGW-Makefiles it goes to `./build/Dictu.exe` no matter what. If you are unsure of where the executable may have ended up, I recommend looking around the build folder for it.

## Epilogue

While I tend to use CMake-Tools rather than the CLI, my setup roughly matches this:

```
cmake -D DISABLE_HTTP=TRUE -D DISABLE_LINENOISE=TRUE -D CMAKE_BUILD_TYPE=<build type> -G "MinGW Makefiles" -S ./ -B ./build
cmake --build ./build
```

After the first call to CMake, due to the aforementioned Cmake caches, it would be more similar to this:

```
cmake -D CMAKE_BUILD_TYPE=<build type> ./build
cmake --build ./build
```

Or even this if the build type is the same as last time:

```
cmake ./build
cmake --build ./build
```

## Author's Note Part 2

After the first build it is possible to mix the generation and the building into one command. Lets say we have generated release version and built it, but now we want to build a debug version. We can run this:

```
cmake --build ./build --config CMAKE_BUILD_TYPE=DEBUG
```

However, this can be problematic. If a new file is added to the source directory, this command will error.

Let's say I have added two files: `header.h` and `header.c`. `header.h` defines `foo` and `header.c` implements `foo`. If I include `header.h` in `main.c` and call `foo` and then run the above command, I get an error stating `foo` was undefined. It works fine if I instead run this:

```
cmake ./build -D CMAKE_BUILD_TYPE=DEBUG
cmake --build ./build
```

The usage of glob in the CMakeLists requires CMake to recheck all source files whenever the generator file is regenerated, however the mixed version of the command does not do this check. If we ever move away from glob and to manual defining of compiled files (See [Author's Note Part 3](#Author's-Note-Part-3)), this will be less of an issue. It may still give odd error messages if you forget to modify the CMakeLists, but after modifying the CMakeLists, you can run the mixed command without concern.

It is possible to use the smaller version for when you haven't added or removed any files and then use the two separate commands for when you have. But if you do mention the combined version, it is also important to mention that it doesn't always work.

## Author's Note Part 3

This Author's Note has far less to do with using the CMake CLI and far more with our current CMakeLists.

For the sake of maintainability and similarity to the Makefile, I used glob for file searching in the CMakeLists. This has consequences covered in [Author's Note Part 2](#Author's-Note-Part-2). I don't have a strong opinion on glob vs manual definitions, however I do hope to clarify how manual definitions could work. Initially, this might seem like it would clutter the CMakeLists to a high degree. But by using `add_subdirectory` and `target_sources`, we can split the logic and the files. We can keep the logic in the main CMakeLists which lives in the main folder and then leave the file collection to sub-CMakeLists in `c`, `c/datatypes` and `c/optionals`. Then, if you add a file to `c/optionals`, you only have to modify `c/optionals/CMakeLists.txt`.

I created an example of this technique here: https://github.com/TheGreatCookieMachine/Sub-CMakeLists-Example

## See also

https://cmake.org/cmake/help/latest/manual/cmake.1.html
https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#manual:cmake-generators(7)
https://cmake.org/runningcmake/ (However this seems to be woefully outdated.)
https://crascit.com/2016/01/31/enhanced-source-file-handling-with-target_sources/ (The source used for most of [Author's Note Part 3](#Author's-Note-Part-3))

**Comment by Jason2605** [comment]
What a fantastic collection of information! Absolutely no need to apologise for the length of the text, it was a great read; obviously as you say probably a bit too much for the README however it gives more than enough to be able to cherry pick the important parts, so thank you very much!
