### ISSUE TITLE
Printing strings adds ' ' around output

### ISSUE THREAD

**Issue by YourLocalDeveloper** [dictu-lang/Dictu#342]
Hello everyone! So I recently discover Dictu and wanted to play around with it. However, when it came to printing strings, ints, etc. I noticed that Dictu does print an object correctly but adds a ' ' around it. For example:
```text
print("Hello world");
```

The console outputs:
```text
'Hello world'
Total memory usage: 0
```

I'm sorry if it seems like I'm nagging, as this was not the intention of this Issue. Is this just a feature of the language or am I missing something? I'm currently running Dictu v0.12.

**Comment by Jason2605** [comment]
Hello there @YourLocalDeveloper!

You are correct, that does happen, Dictu will wrap strings in single quotes before printing it to the screen. The reasoning for this is you can easily work out the type of something when it is being printed (mainly added for the REPL).

There will more than likely be cases where printing strings to the screen should not result in the quote wrapping and I'm open to changing this so that only the REPL would wrap a returned string in quotes.

> I'm sorry if it seems like I'm nagging
Don't worry about this, your question was perfectly fine and I welcome anymore you may have in the future 😄

**Comment by YourLocalDeveloper** [comment]
Hello @Jason2605 
Thank you for the fast reply! I can totally see the reasoning behind using single quotes in such a manner. Have a great day!
