### ISSUE TITLE
[BUG] Tests failing on Apple M1

### ISSUE THREAD

**Issue by gvwilson** [dictu-lang/Dictu#493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using version e008a7c62:

- `getFrameCount` test fails:

```
Error: File 'tests/inspect/getFile.du', line 10
       Optional argument passed to getFile() exceeds the frame count.
```

- `strptime` test fails (note: `Datetime.strptime("%Y", "2020")` returns `1577854800` not `1577856800` (a difference of 2000)

```
Error: File 'tests/datetime/strptime.du', line 12
       assert() was false!
```

- `tests/system/access.du` fails

```
Error: File 'tests/system/access.du', line 20
       assert() was false!
```

There are a few others - please let me know if these are symptoms of a configuration or build error on my part, and if not, I'll send a full list.

### Expected Behavior

All tests should pass.

### Steps To Reproduce

1. `cmake -DCMAKE_BUILD_TYPE=Debug -B ./build`
2. `cmake --build ./build`
3. `./dictu tests/runTests.du`

### Anything else?

```
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: arm64-apple-darwin20.6.0
```

**Comment by Jason2605** [comment]
Thanks very much for this @gvwilson!

The frameCount one will more than likely be to you running that file directly. It's probably not a great test, but it expects you to run it via `tests/runTests.du`. The reason for this is due to it being down a nested import route, so the frameCount is higher.

The strptime test failing makes me think it's a timezone issue since EST is GMT-5 and there's a difference of 5 hours between those two values!

The `tests/system/access.du` tests is actually a great spot! They're not included in the import file so they're not being ran as part of the Actions process (or manually when running runTests.du) - will sort that!
