### ISSUE TITLE
[FEATURE] - Add ability to use module values in annotations

### ISSUE THREAD

**Issue by briandowns** [dictu-lang/Dictu#555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I was messing around with annotations and was hoping I could use the value from the HTTP module as an argument to a class annotation and was unable to do so. 

Another aspect of this that would be nice is to be able to use annotations from modules.

### Describe the solution you'd like

Ideally, I'd like to be able to do this on classes as well as methods, and possibly even class members. 

```cs
import HTTP;

@Methods(HTTP.METHOD_GET)
class UserController {
    // ...
}
```

Annotation from a module:

```cs
import HTTP;
import someRestFramework;

@someRestFramework.Methods(HTTP.METHOD_GET)
class User < someRestFramework.Controller {
    // ...
}
```

**Comment by Jason2605** [comment]
Hey! Annotations are one that are in need of some loving and are only partly complete unfortunately (#464). The issue here though is that annotations are actually created at compile time, and not at runtime. This is the reason there's a hard requirement on a literal value being placed there. The actual annotation identifier itself is also just transformed into a string and placed into a dictionary as a key, this means you don't need to do any sorts of imports to use an annotation.

E.g:
```js
import HTTP;
import someRestFramework;

@Methods("GET")
class User < someRestFramework.Controller {
    // ...
}
```

**Comment by briandowns** [comment]
Great info. All of that makes sense. Thanks!
