### ISSUE TITLE
[FEATURE] - Template Module

### ISSUE THREAD

**Issue by briandowns** [dictu-lang/Dictu#578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I was hoping to get your (@Jason2605) feedback on the idea of adding a `Template` module that was based around the template engine example I have in the examples directory [here](https://github.com/dictu-lang/Dictu/blob/develop/examples/templateEngine.du).

This would initially start out similar to the current implementation with the intent of extension similar to how Go has one for generalized text and another for HTML content, within its stdlib.

### Describe the solution you'd like

I'd adapt the example linked above (that exists in the examples directory) to be a stdlib module written in Dictu.

**Comment by Jason2605** [comment]
Yeah this is something I’ve thought about previously. Both Python and Node expose variable interpolation directly into the string as part of essentially the syntax of the language and it’s something I’ve thought about for some time whether Dictu should also do. The R strings in Dictu (raw no special character parsing e.g \n) is the exact same syntax as Python, so we could follow suite and expose F strings in Dictu. 

It’s something that I think is definitely better as a user experience but my concern is essentially if we should embed it into the language itself rather than as an additional module. For reference Wren also has a similar type of construct that we could piggyback the C code for!

**Comment by briandowns** [comment]
Yeah, all good points. Ok, time to give it some more though. Thanks!
