### ISSUE TITLE
Build method for windows machines

### ISSUE THREAD

**Issue by Jason2605** [dictu-lang/Dictu#90]
Currently there’s no way to build Dictu on windows.

**Comment by MrFrydae** [comment]
When the user executes 'make' on a Windows system, it either installs a dual boot and compiles on linux, or installs the windows subsystem for linux and compiles using that. I am not saying that this will be a very time efficient method, but it will be very effective.

**Comment by NightShade256** [comment]
Building on Windows is very much doable.

We could use [CMake](https://cmake.org/) to be OS agnostic.
I could make a `CMakeLists.txt` but it would nullify the existing testing workflow on Github Actions, so we would have to account for that.

**Comment by NightShade256** [comment]
If you want me to go ahead, I will happily do so.

**Comment by Jason2605** [comment]
Hi @NightShade256, I'd be very happy for you to attempt to get a build of Dictu working on Windows, we can always review the testing method on Actions - that's no problem. Obviously with this when building on windows there may be some unknowns when attempting to build so that could be quite tricky to solve at times.

Will assign this to you!

**Comment by NightShade256** [comment]
@Jason2605 I think adding cURL as a git submodule will massively simplify the build experience for both the developers and the end users. If you allow it I can do it that way.

Also should I make a separate PR or since I already have one opened #268 push this as a commit to that PR?

**Comment by Jason2605** [comment]
@NightShade256 Definitely something to look into if it will ease the building process.

Separate PR per item please!

**Comment by NightShade256** [comment]
@Jason2605 I have hit a snag.

In `optionals/system.h` you include `sys/utsname.h` , which AFAIK is a POSIX header and hence unavailable on Windows.
(Even on MinGW-w64 for that matter)

This issue must be resolved before further progress.

**Comment by Jason2605** [comment]
Yeah i had a feeling this would be the case. I'm still curious to see where you go up to with your CMake conversion however, and we can slowly work through the Dictu source to try and make it more "OS independent". Appreciate you looking into this by the way!

**Comment by NightShade256** [comment]
@Jason2605 

I have actually made the `CMakeLists.txt` file, it compiles successfully on Linux currently (on my machine) for the debug and release profiles.
But since due to above issues, the scope of the port to Windows has widened from simply rewriting the build files to rewriting chunks of the interpreter itself. Plus there is the cURL dependency it would either require users to use `vcpkg` or we would have to bundle the headers and static library through this repository.

I think this issue should currently be dropped till those other problems are solved.

**Comment by Jason2605** [comment]
It kind of goes hand in hand, there needs to be updated make files before we attempt the re-writing stage of the interpreter as we need to be able to actually build; while i agree the scope has widened (as expected) this task will still need to be done.

Perhaps worth making some extra issues about the notes you've made above (shame we can't have "sub issues").

**Comment by NightShade256** [comment]
As for the CMake file, I have pushed that to a branch on my fork, it works for Linux (and should therefore for macOS too).
It can be extended to Windows if we figure out the `linenoise` issue and the system issue.

Then we could atleast build the interpreter without HTTP support.

**Comment by Jason2605** [comment]
Perfect thank you! I'll be able to test it on MacOS so thats not an issue. Will take a look at the issues you've noted above and i'll drop my progress as/when on this issue.

**Comment by TheGreatCookieMachine** [comment]
I would like to let you guys know that I am working on solutions to Windows build and runtime bugs right now. It ended up being a bigger project than I thought, so it may take me a couple more days. Certain features have been disabled for now, such as replacing linenoise with a far more basic repl for Windows. While I did make a CMakeLists, it is not as good as the one created by NightShade, so I won't include it in the PR.

**Comment by Jason2605** [comment]
Thats awesome @TheGreatCookieMachine! Looking forward to hearing your progress over the next coming days

**Comment by TheGreatCookieMachine** [comment]
Update:
I now have commit e5616d70f8306242e168e5934ae1bc8af87c66a3 compiling on Windows using tdm64 gcc 9.2.0, clang 9.0.0 using MSVC's libc, and Visual Studio 16.5.4. I originally stated that I wasn't going to include my CMakeLists, however I ended up making certain changes to the defines and linked libraries. I can't run the provided Makefile and don't want to change it without being able to run it, so I committed the CMakeLists so that the commit could be properly compiled. If anyone would like to replace the CMakeLists later, feel free.
Clang and MSVC currently spit out warnings meaning I can't turn on `/WX` (MSVC's version of -Werror), so I will have to fix those before creating the pull request. Most of them are deprecation warnings (MSVC's deprecations tend to be liberally passed out). I also can't turn on `/W3` or `/W4` (I haven't tested the others yet) due to them having warnings about implicit conversions, which GCC doesn't. Fixing these warnings would require a lot of changes which aren't directly related to Windows compatibility and many of the issues would likely return over time due to GCC not checking them. I also have to update my branch to the head and make sure no new errors pop up.
A few of the MSVC errors, such as not having the "blocks with returns" extension, can be caught on GCC using `-pedantic`, but `-pedantic` disallows computed gotos. As such, it has been left off.
I will go over more detail on what I changed and why and possible issues with these changes in the pull request.
Lastly, I am unable to test if the code still compiles and works on a non-Windows system. While I think it should, I cannot guarantee that fact.

**Comment by Jason2605** [comment]
That seems like a lot of progress, awesome work! Don’t worry about testing on non-windows machines, I’ll be able to test and provide feedback on those systems. I look forward to the PR you create and the discussion that will go along with it!
